### ISSUE TITLE
 Error: com.tns.NativeScriptException: Failed to find module: "nativescript-openfile", relative to: app/tns_modules/

### ISSUE THREAD

**Issue by addean** [elmissouri16/nativescript-openfile#2]
app cannot start due to the error stated

**Comment by elmissouri16** [comment]
did you load the module correctly

**Comment by leocrawf** [comment]
I also have the exact same issue.

**Comment by elmissouri16** [comment]
@addean  @leocrawf I think is related to tns version need to be updated  i well updated soon

**Comment by Byenkya** [comment]
i also have the same issue
